name: Full Build - Open PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

  merge_group:
    types:
      - checks_requested

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install root dependencies
        run: npm install

      - name: Run build
        run: npm run build
