name: Build & Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main, dev]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format:check

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm run test
