name: Commands - Open PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

  merge_group:
    types:
      - checks_requested

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install root dependencies
        run: npm install

      - name: Run coverage
        run: npm run test:coverage

      - name: Run lint
        run: npm run lint
